-- Fix all columns to ensure they can store proper values
ALTER TABLE survey_responses ALTER COLUMN q1 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q2 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q3 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q4 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q5 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q6 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q7 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q8 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q9 TYPE TEXT;
ALTER TABLE survey_responses ALTER COLUMN q10 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q11 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q12 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q13 TYPE VARCHAR(10);
