-- Add demographic columns and update existing columns
ALTER TABLE survey_responses ADD COLUMN IF NOT EXISTS q0a VARCHAR(10);
ALTER TABLE survey_responses ADD COLUMN IF NOT EXISTS q0b VARCHAR(10);
ALTER TABLE survey_responses ADD COLUMN IF NOT EXISTS q14 VARCHAR(10);
ALTER TABLE survey_responses ADD COLUMN IF NOT EXISTS q15 TEXT;

-- Ensure all columns have proper types
ALTER TABLE survey_responses ALTER COLUMN q1 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q2 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q3 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q4 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q5 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q6 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q7 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q8 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q9 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q10 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q11 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q12 TYPE VARCHAR(10);
ALTER TABLE survey_responses ALTER COLUMN q13 TYPE VARCHAR(10);
